---
- name: Check and update sssd configuration
  hosts: all
  become: true
  tasks:

    - name: Check if ymus.conf exists and service is running
      block:
        - name: Check if ymus.conf exists
          stat:
            path: /etc/sssd/conf.d/ymus.conf
          register: sssd_conf_file

        - name: Check if sssd service is running
          service:
            name: sssd
            state: started
          register: sssd_service_status

      rescue:
        - name: Report error if ymus.conf does not exist or service is not running
          fail:
            msg: "Not using sssd or the file /etc/sssd/conf.d/ymus.conf does not exist"

    - name: Check if ldap_referrals=false is already present
      block:
        - name: Search for ldap_referrals=false in ymus.conf
          shell: grep -q '^ldap_referrals=false' /etc/sssd/conf.d/ymus.conf
          register: ldap_referrals_check
          failed_when: false
          changed_when: false

        - name: Skip subsequent tasks if ldap_referrals=false exists
          when: ldap_referrals_check.rc == 0
          debug:
            msg: "ldap_referrals=false is already present in the configuration. No changes needed."

    - name: Handle backup and file replacement
      when: ldap_referrals_check.rc != 0
      block:
        - name: Check if backup file exists
          stat:
            path: /etc/sssd/conf.d/ymus.conf.20250122
          register: backup_file_check

        - name: End play if backup file exists
          when: backup_file_check.exists
          debug:
            msg: "Backup file /etc/sssd/conf.d/ymus.conf.20250122 already exists. No changes made."

        - name: Create backup of ymus.conf
          when: not backup_file_check.exists
          copy:
            src: /etc/sssd/conf.d/ymus.conf
            dest: /etc/sssd/conf.d/ymus.conf.20250122

        - name: Replace ymus.conf with new file
          when: not backup_file_check.exists
          copy:
            src: ymus.conf
            dest: /etc/sssd/conf.d/ymus.conf
          notify: Restart sssd

  handlers:
    - name: Restart sssd
      service:
        name: sssd
        state: restarted
