---
- name: Update all packages to the latest version
  hosts: all
  become: yes

  tasks:
    - name: Ensure all packages are up to date
      yum:
        name: '*'
        state: latest
      register: update_result

    - name: Reboot the server if any packages were updated
      reboot:
      when: update_result.changed
      ignore_errors: yes
