---
- name: Post Installation Steps for New Oracle 8.5
  hosts: tsansed1
  gather_facts: no
  tasks:
  - name: Install bind-utils, nmap, chrony
    ansible.builtin.yum:
      name:
        - bind-utils
        - nmap
        - chrony
      state: latest

  - name: Insert local time server to chrony.conf
    lineinfile:
      path: /etc/chrony.conf
      line: "server 167.174.145.248"
      insertbefore: "^pool 2.pool.ntp.org iburst"
    notify: restart chronyd

  - name: Modify group 'games'
    command: groupmod -g 25 games
    become: true

  - name: Check if group 'techsupp' exists
    command: getent group techsupp
    register: group_check
    ignore_errors: true

  - name: Add group 'techsupp' if it does not exist
    command: groupadd -g 20 techsupp
    when: group_check.rc != 0
    become: true

  - name: Ensure oddjob, sssd, openldap-clients, sssd-ldap, and openssl-perl are installed
    yum:
      name: "{{ item }}"
      state: present
    with_items:
      - sssd
      - oddjob-mkhomedir
      - openldap-clients
      - sssd-ldap
      - openssl-perl

  - name: Ensure sssd and oddjob are enabled and running
    systemd:
      name: "{{ item }}"
      enabled: yes
      state: started
    with_items:
      - sssd
      - oddjobd

  - name: Copy ymus-NTCAR2-SHA256.cer to target host
    ansible.builtin.copy:
      src: ymus-NTCAR2-SHA256.cer
      dest: /etc/pki/ca-trust/source/anchors/ymus-NTCAR2-SHA256.cer
      checksum: yes
      owner: root
      group: root
      mode: 0644
      
  - name: Copy ymus.conf to target host
    ansible.builtin.copy:
      src: ymus.conf
      dest: /etc/sssd/conf.d/ymus.conf
      checksum: yes
      owner: root
      group: root
      mode: 0600

  - name: Run authselect command
    command: authselect select sssd with-mkhomedir --force
    
  - name: Restart oddjobd service
    systemd:
      name: oddjobd
      state: restarted

  - name: Restart sssd service
    systemd:
      name: sssd
      state: restarted

  - name: Get user tss
    command: getent passwd | grep tss
    register: tss_user

  - name: Debug output for AD Integration
    debug:
      msg: "{{ tss_user.stdout }}"


  - name: Install make, sendmail, sendmail-cf, and mailx
    dnf:
      name: "{{ item }}"
      state: present
    loop:
      - make
      - sendmail
      - sendmail-cf
      - mailx


  handlers:
    - name: restart chronyd
      systemd:
        name: chronyd
        state: restarted